name: ithera
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  camera: ^0.10.5+2 # Allows access to the device's camera for real-time image capture.
  sqflite:       # Provides SQLite database support for storing app data locally.
  path:            # Offers utilities for handling and manipulating file paths.
  cupertino_icons: ^1.0.8  # Provides Cupertino styled icons for iOS design consistency.
  shared_preferences: ^2.2.2  # Enables storing simple data types persistently across app launches.
  google_fonts: ^6.2.1  # To use google fonts
  url_launcher: ^6.3.0 # Allows launching URLs in the app
  image_picker: ^1.0.4  # Enables picking images from the gallery
  path_provider: ^2.1.1  # Provides platform-aware locations for storing app-specific files.
  audioplayers: ^5.2.0 # For playing audio files
  tflite_flutter: ^0.11.0
  image: ^4.2.0
  google_mlkit_face_detection: 0.13.0 # Added for face detection

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png   #logo
    - assets/background.jpg    #background
    - assets/labels.txt   #emotion labels
    - assets/model.tflite #tflite model
    - assets/sound-cards/ocean.jfif   #6 sound cards
    - assets/sound-cards/forest.jfif
    - assets/sound-cards/rain.jpg
    - assets/sound-cards/chimes.jpg
    - assets/sound-cards/bird.jfif
    - assets/sound-cards/fire.jpg
    - assets/sounds/ocean_waves.mp3     #6 sounds
    - assets/sounds/forest_ambience.m4a
    - assets/sounds/rainfall.m4a
    - assets/sounds/wind_chimes.m4a
    - assets/sounds/bird_song.m4a
    - assets/sounds/fire.m4a
    - assets/yt-cards/1.jpg  #4 YT thumps
    - assets/yt-cards/2.jpg
    - assets/yt-cards/3.jpg
    - assets/yt-cards/4.jpg
